<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Мой тестовый сайт</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f0f0f0;
        }
        h1 {
            color: #2c3e50;
            text-align: center;
        }
        .content {
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        button {
            padding: 10px 20px;
            background: #3498db;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="content">
        <h1>Добро пожаловать на мой сайт! 🚀</h1>
        <p>Это тестовая страница для GitHub Pages</p>
        <button onclick="showMessage()">Нажми меня</button>
        <p id="message"></p>
    </div>

    <script>
        function showMessage() {
            const messages = [
                "Вы великолепны! 🌟",
                "Отличная работа! 👍",
                "GitHub Pages работает! 🎉",
                "Продолжайте в том же духе! 💪"
            ];
            const randomMessage = messages[Math.floor(Math.random() * messages.length)];
            document.getElementById('message').textContent = randomMessage;
        }
    </script>
</body>
</html>
